syntax = "proto3";

/* 
  This module defines services intended for us
  *receiving* real-time data from the MOT (ministry of transport) 
  or any other source.
*/ 

package vehicle_monitoring;

import "ptproto/common/types.proto";

message VehicleMonitoringUpdatesBatch {
  repeated common.SingleVehicleMonitoring updates = 1;
}

message SendVehicleMonitoringResponse {
  bool accepted = 1;
}

service VehicleMonitoringService {
  rpc Send(common.SingleVehicleMonitoring) returns (SendVehicleMonitoringResponse);
  rpc SendBatch(VehicleMonitoringUpdatesBatch) returns (SendVehicleMonitoringResponse);
}